### ISSUE TITLE
Error in menu command

### ISSUE THREAD

**Issue by astorm** [astorm/pestle#183]
$ pestle.phar magento2:generate:menu
Module Name? (Pulsestorm_HelloGenerate)] Pulsestorm_Pestleform
No such function [input] imported for namespace [Pulsestorm\Magento2\Cli\Magento2\Generate\Menu]Alans-MacBook-Pro:project-community-edition alanstorm$

**Comment by astorm** [comment]
Also PHP Fatal error:  Uncaught Error: Call to undefined function Pulsestorm\Magento2\Cli\Magento2\Generate\Menu\choseMenuFromTop() in /Users/alanstorm/Documents/github/astorm/pestle/modules/pulsestorm/magento2/cli/magento2/generate/menu/module.php:19
Stack trace:
#0 [internal function]: Pulsestorm\Magento2\Cli\Magento2\Generate\Menu\selectParentMenu(Array, 1)
#1 /Users/alanstorm/Documents/github/astorm/pestle/modules/pulsestorm/pestle/runner/module.php(288): ReflectionFunction->invokeArgs(Array)
#2 /Users/alanstorm/Documents/github/astorm/pestle/modules/pulsestorm/pestle/runner/module.php(324): Pulsestorm\Pestle\Runner\limitArgumentsIfPresentInDocBlock(Array, Array, Object(ReflectionFunction))
#3 /Users/alanstorm/Documents/github/astorm/pestle/modules/pulsestorm/pestle/runner/module.php(364): Pulsestorm\Pestle\Runner\getArgumentsAndOptionsFromParsedArgvAndDocComment(Array, Array, Object(ReflectionFunction))
#4 /Users/alanstorm/Documents/github/astorm/pestle/runner.php(5): Pulsestorm\Pestle\Runner\main(Array)
#5 /Users/alanstorm/Do in /Users/alanstorm/Documents/github/astorm/pestle/modules/pulsestorm/magento2/cli/magento2/generate/menu/module.php on line 19
