### ISSUE TITLE
Grid Generation Initial AJAX Request errors in 2.1.3

### ISSUE THREAD

**Issue by astorm** [astorm/pestle#184]
1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): Invalid method Pulsestorm\Pestleform\Model\Reply::addOrder

Exception #0 (Magento\Framework\Exception\LocalizedException): Invalid method Pulsestorm\Pestleform\Model\Reply::addOrder
#0 /Users/alanstorm/Sites/magento-2-1-3.dev/project-community-edition/vendor/magento/module-ui/DataProvider/AbstractDataProvider.php(202): Magento\Framework\DataObject->__call('addOrder', Array)
#1 /Users/alanstorm/Sites/magento-2-1-3.dev/project-community-edition/vendor/magento/module-ui/Component/Listing/Columns/Column.php(136): Magento\Ui\DataProvider\AbstractDataProvider->addOrder('pulsestorm_pest...', 'ASC')

**Comment by astorm** [comment]
Looks like we're injecting a model when what we need is a collection.  Change generation code to the uncommented thing is generated.

        // \Pulsestorm\Pestleform\Model\ReplyFactory $collectionFactory,
        \Pulsestorm\Pestleform\Model\ResourceModel\Reply\CollectionFactory $collectionFactory,

**Comment by astorm** [comment]
This was fixed a while back -- looks like we missed closing out this issue. Yay!
