### ISSUE TITLE
FIx Packaging Problem

### ISSUE THREAD

**Issue by astorm** [astorm/pestle#232]
BUILD FAILED
    /private/tmp/build/pestle/build.xml:41:117: /private/tmp/build/pestle/build.xml:41:117: Problem creating package: unable to create temporary file
    #0 /private/tmp/build/pestle/vendor/phing/phing/classes/phing/UnknownElement.php(100): PharPackageTask->main()
    #1 /private/tmp/build/pestle/vendor/phing/phing/classes/phing/Task.php(283): UnknownElement->main()
    #2 /private/tmp/build/pestle/vendor/phing/phing/classes/phing/Target.php(336): Task->perform()
    #3 /private/tmp/build/pestle/vendor/phing/phing/classes/phing/Target.php(366): Target->main()
    #4 /private/tmp/build/pestle/vendor/phing/phing/classes/phing/Project.php(898): Target->performTasks()
    #5 /private/tmp/build/pestle/vendor/phing/phing/classes/phing/Project.php(868): Project->executeTarget('package_phar')
    #6 /private/tmp/build/pestle/vendor/phing/phing/classes/phing/Phing.php(723): Project->executeTargets(Array)
    #7 /private/tmp/build/pestle/vendor/phing/phing/classes/phing/Phing.php(200): Phing->runBuild()
    #8 /private/tmp/build/pestle/vendor/phing/phing/classes/phing/Phing.php(347): Phing::start(Array, NULL)
    #9 /private/tmp/build/pestle/vendor/phing/phing/bin/phing.php(58): Phing::fire(Array)
    #10 /private/tmp/build/pestle/vendor/phing/phing/bin/phing(14): require_once('/private/tmp/bu...')
    #11 {main}

**Comment by astorm** [comment]
https://blog.dekstroza.io/ulimit-shenanigans-on-osx-el-capitan/

**Comment by astorm** [comment]
Thanks for the 256 open file limit Apple!
